apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - name: test
    image: ubuntu:14.04.3
    command: ["/bin/sh", "-c"]
    args: ["sleep 3600"]
    ports:
    - containerPort: 80
